root: true
parserOptions:
  ecmaVersion: latest
env:
  browser: true
  jest: true
extends:
  - standard
  - 'plugin:vue/vue3-recommended'
  - tjw-jsdoc
rules:
  'import/no-default-export': 'off'
  "vue/multi-word-component-names": "off"
  "vue/no-multiple-template-root": "off"
  "vue/max-attributes-per-line":
    - "error"
    - singleline:
        max: 3
      multiline:
        max: 1
  "jsdoc/require-jsdoc": "off"
  "jsdoc/require-file-overview": "off"
  quotes:
    - error
    - single
overrides:
  - files: '*.mjs'
globals:
  $fetch: readonly
